spring:
  datasource:
    url: jdbc:h2:mem:invitation;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
